//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Status { get; set; }
    public bool Publish { get; set; }
    public string Images { get; set; }
    public Nullable<int> RelativeProductIds { get; set; }
    public decimal Price { get; set; }
    public string Currency { get; set; }
    public System.DateTime CreatedDate { get; set; }
}
