//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class WebsiteTTKEntities : DbContext
{
    public WebsiteTTKEntities()
        : base("name=WebsiteTTKEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
    public virtual DbSet<AspNetUserAddress> AspNetUserAddresses { get; set; }
    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<brand> brands { get; set; }
    public virtual DbSet<category> categories { get; set; }
    public virtual DbSet<colour> colours { get; set; }
    public virtual DbSet<product> products { get; set; }
    public virtual DbSet<stock> stocks { get; set; }
    public virtual DbSet<customer> customers { get; set; }
    public virtual DbSet<order_items> order_items { get; set; }
    public virtual DbSet<order> orders { get; set; }
    public virtual DbSet<staff> staffs { get; set; }
    public virtual DbSet<store> stores { get; set; }
}
